# Generated by Django 5.0.14 on 2025-10-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='extracted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
    ]
