# Generated by Django 5.0.14 on 2025-10-21 01:20

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_certificate_extracted_date_certificate_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(max_length=255, upload_to=employees.models.certificate_upload_path, verbose_name='Arquivo'),
        ),
    ]
