# Generated by Django 5.0.14 on 2025-11-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
